// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentMS.DAL;

namespace PaymentMS.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200219160928_UpdatePaymentTable")]
    partial class UpdatePaymentTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentMS.DAL.Entities.ApiLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(32);

                    b.Property<string>("Logs")
                        .HasMaxLength(8192);

                    b.Property<string>("PathToAction")
                        .HasMaxLength(1024);

                    b.Property<int>("ResponseCode");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("ApiLogs");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.BalanceClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<Guid>("BalanceProviderId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("OrganizationId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BalanceProviderId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BalanceClients");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.BalanceProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<bool>("IsStripeCardIncomeEnabled");

                    b.Property<bool>("IsWireTransferIncomeEnabled");

                    b.Property<Guid>("OrganizationId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BalanceProviders");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BalanceClientId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(2048);

                    b.Property<Guid>("ExternalId");

                    b.Property<string>("ExternalMetadata")
                        .HasMaxLength(2048);

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<string>("PaymentCurrency")
                        .HasMaxLength(8);

                    b.Property<int>("PaymentMethod");

                    b.Property<Guid?>("SendingWayId");

                    b.Property<int>("Status");

                    b.Property<string>("TransactionLog")
                        .HasMaxLength(8192);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BalanceClientId");

                    b.HasIndex("SendingWayId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.ReceivingWayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BalanceProviderId");

                    b.Property<string>("Configuration");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("OrganizationId");

                    b.Property<int>("PaymentMethod");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BalanceProviderId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("PaymentReceivingWays");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.SendingWayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Configuration")
                        .HasMaxLength(4096);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsDefault");

                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid>("ReceivingWayId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ReceivingWayId");

                    b.ToTable("PaymentSendingWays");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.BalanceClientEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.BalanceProviderEntity", "BalanceProvider")
                        .WithMany()
                        .HasForeignKey("BalanceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany("BalanceClients")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.BalanceProviderEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany("BalanceProviders")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.PaymentEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.BalanceClientEntity", "BalanceClient")
                        .WithMany("Payments")
                        .HasForeignKey("BalanceClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.SendingWayEntity", "SendingWay")
                        .WithMany("Payments")
                        .HasForeignKey("SendingWayId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.ReceivingWayEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.BalanceProviderEntity", "BalanceProvider")
                        .WithMany("ReceivingWays")
                        .HasForeignKey("BalanceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany("ReceivingWays")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.SendingWayEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany("SendingWays")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.ReceivingWayEntity", "ReceivingWay")
                        .WithMany("SendingWays")
                        .HasForeignKey("ReceivingWayId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
