// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentMS.DAL;

namespace PaymentMS.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200611091118_AddCurrencyExchangeConfig")]
    partial class AddCurrencyExchangeConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentMS.DAL.Entities.ApiLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<long>("ExecutionTimeInMilliSec");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(32);

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<string>("Logs")
                        .HasMaxLength(8192);

                    b.Property<string>("PathToAction")
                        .HasMaxLength(1024);

                    b.Property<int>("ResponseCode");

                    b.HasKey("Id");

                    b.ToTable("ApiLogs");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.BalanceClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<Guid>("BalanceProviderId");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<Guid>("OrganizationId");

                    b.HasKey("Id");

                    b.HasIndex("BalanceProviderId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BalanceClients");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.BalanceProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<bool>("IsStripeCardIncomeEnabled");

                    b.Property<bool>("IsWireTransferIncomeEnabled");

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<Guid>("OrganizationId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BalanceProviders");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.CurrencyEntity", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8);

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Code");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.CurrencyExchangeConfigEntity", b =>
                {
                    b.Property<string>("FromCurrencyCode");

                    b.Property<string>("ToCurrencyCode");

                    b.Property<Guid>("OrganizationId");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<decimal?>("CustomRate")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<int>("ExchangeProvider");

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<decimal>("Surcharge")
                        .HasColumnType("decimal(26, 10)");

                    b.HasKey("FromCurrencyCode", "ToCurrencyCode", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ToCurrencyCode");

                    b.ToTable("CurrencyExchangeConfigs");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.CurrencyExchangeRateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<DateTime>("ExchangeDate");

                    b.Property<int>("ExchangeProvider");

                    b.Property<string>("FromCurrencyCode");

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<Guid?>("OrganizationId");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("ToCurrencyCode");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeDate");

                    b.HasIndex("ExchangeProvider");

                    b.HasIndex("FromCurrencyCode");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ToCurrencyCode");

                    b.ToTable("CurrencyExchangeRates");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BalanceClientId");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(2048);

                    b.Property<Guid>("ExternalId");

                    b.Property<string>("ExternalMetadata")
                        .HasMaxLength(2048);

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(26, 10)");

                    b.Property<string>("PaymentCurrency")
                        .HasMaxLength(8);

                    b.Property<int>("PaymentMethod");

                    b.Property<Guid?>("SendingWayId");

                    b.Property<int>("Status");

                    b.Property<string>("TransactionLog")
                        .HasMaxLength(8192);

                    b.HasKey("Id");

                    b.HasIndex("BalanceClientId");

                    b.HasIndex("SendingWayId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.ReceivingWayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BalanceProviderId");

                    b.Property<string>("Configuration");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<Guid>("OrganizationId");

                    b.Property<int>("PaymentMethod");

                    b.HasKey("Id");

                    b.HasIndex("BalanceProviderId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("PaymentReceivingWays");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.SendingWayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Configuration")
                        .HasMaxLength(4096);

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<bool>("IsDefault");

                    b.Property<DateTime>("LastUpdatedDateUtc");

                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid>("ReceivingWayId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ReceivingWayId");

                    b.ToTable("PaymentSendingWays");
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.BalanceClientEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.BalanceProviderEntity", "BalanceProvider")
                        .WithMany()
                        .HasForeignKey("BalanceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany("BalanceClients")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.BalanceProviderEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany("BalanceProviders")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.CurrencyExchangeConfigEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.CurrencyEntity", "FromCurrencyEntity")
                        .WithMany()
                        .HasForeignKey("FromCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.CurrencyEntity", "ToCurrencyEntity")
                        .WithMany()
                        .HasForeignKey("ToCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.CurrencyExchangeRateEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.CurrencyEntity", "FromCurrencyEntity")
                        .WithMany()
                        .HasForeignKey("FromCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.CurrencyEntity", "ToCurrencyEntity")
                        .WithMany()
                        .HasForeignKey("ToCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.PaymentEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.BalanceClientEntity", "BalanceClient")
                        .WithMany("Payments")
                        .HasForeignKey("BalanceClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.SendingWayEntity", "SendingWay")
                        .WithMany("Payments")
                        .HasForeignKey("SendingWayId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.ReceivingWayEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.BalanceProviderEntity", "BalanceProvider")
                        .WithMany("ReceivingWays")
                        .HasForeignKey("BalanceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany("ReceivingWays")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaymentMS.DAL.Entities.SendingWayEntity", b =>
                {
                    b.HasOne("PaymentMS.DAL.Entities.OrganizationEntity", "Organization")
                        .WithMany("SendingWays")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaymentMS.DAL.Entities.ReceivingWayEntity", "ReceivingWay")
                        .WithMany("SendingWays")
                        .HasForeignKey("ReceivingWayId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
